import "./globals.css";
import { Poppins } from "next/font/google";

// Subsets are really important. CHECK BELOW FOR MORE INFO
const poppins = Poppins({ weight: "200", subsets: ["latin"] });
export const metadata = {
  title: "BPB-Business Permit ng Bayan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://res.cloudinary.com/dm1hejbuu/image/upload/v1691674279/endUser/SARIAYA-SEAL1_etumcp.jpg"
        />
      </head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
